-- Dynamic pricing schema for Farmmily.
-- Admin stores one base price per kg in `products`.
-- Variants store only weight and stock in `product_variants`.
-- Customer-side and admin-side both calculate final price dynamically.

create extension if not exists pgcrypto;

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  description text,
  image_url text,
  category_id bigint,
  base_price_per_kg numeric(10,2) not null check (base_price_per_kg >= 0),
  is_active boolean not null default true,
  is_featured boolean not null default false,
  rating numeric(3,1) not null default 5.0,
  review_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table products add column if not exists slug text;
alter table products add column if not exists description text;
alter table products add column if not exists image_url text;
alter table products add column if not exists category_id bigint;
alter table products add column if not exists is_active boolean not null default true;
alter table products add column if not exists is_featured boolean not null default false;
alter table products add column if not exists rating numeric(3,1) not null default 5.0;
alter table products add column if not exists review_count integer not null default 0;
alter table products add column if not exists created_at timestamptz not null default now();
alter table products add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'products'
      and column_name = 'base_price'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'products'
      and column_name = 'base_price_per_kg'
  ) then
    alter table products rename column base_price to base_price_per_kg;
  end if;
end $$;

alter table products add column if not exists base_price_per_kg numeric(10,2);
update products set base_price_per_kg = 0 where base_price_per_kg is null;
alter table products alter column base_price_per_kg set default 0;
alter table products alter column base_price_per_kg set not null;

create table if not exists product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  weight_kg numeric(10,2) not null check (weight_kg > 0),
  stock_count integer not null default 0 check (stock_count >= 0),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, weight_kg)
);

alter table product_variants add column if not exists stock_count integer not null default 0;
alter table product_variants add column if not exists is_active boolean not null default true;
alter table product_variants add column if not exists sort_order integer not null default 0;
alter table product_variants add column if not exists created_at timestamptz not null default now();
alter table product_variants add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'product_variants'
      and column_name = 'weight'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'product_variants'
      and column_name = 'weight_kg'
  ) then
    alter table product_variants rename column weight to weight_kg;
  end if;
end $$;

alter table product_variants add column if not exists weight_kg numeric(10,2);
update product_variants set weight_kg = 0 where weight_kg is null;
alter table product_variants alter column weight_kg set default 0;
alter table product_variants alter column weight_kg set not null;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'product_variants'
      and column_name = 'label'
  ) then
    null;
  end if;
end $$;

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_products_updated_at on products;
create trigger trg_products_updated_at
before update on products
for each row
execute function set_updated_at();

drop trigger if exists trg_product_variants_updated_at on product_variants;
create trigger trg_product_variants_updated_at
before update on product_variants
for each row
execute function set_updated_at();

create or replace view product_variant_prices as
select
  pv.id as variant_id,
  p.id as product_id,
  p.name as product_name,
  p.slug,
  p.description,
  p.image_url,
  p.category_id,
  p.base_price_per_kg,
  pv.weight_kg,
  concat(trim(to_char(pv.weight_kg, '999990.##')), ' kg') as weight_label,
  pv.stock_count,
  pv.is_active as variant_is_active,
  p.is_active as product_is_active,
  round(p.base_price_per_kg * pv.weight_kg, 2) as variant_price
from product_variants pv
join products p on p.id = pv.product_id;

comment on view product_variant_prices is
'Read-only view for storefront/admin lists. Variant price is calculated from products.base_price_per_kg * product_variants.weight_kg.';

-- Sample data
insert into products (id, name, slug, description, image_url, base_price_per_kg, is_active, is_featured)
values
  (101, 'Imam Pasand Mango', 'imam-pasand-mango', 'Premium Imam Pasand mangoes priced per kg.', 'assets/imam.png', 349.00, true, true),
  (102, 'Alphonso Mango', 'alphonso-mango', 'Sweet Alphonso mangoes priced per kg.', 'assets/alphonso.png', 299.00, true, true)
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  image_url = excluded.image_url,
  base_price_per_kg = excluded.base_price_per_kg,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured;

insert into product_variants (product_id, weight_kg, stock_count, is_active, sort_order)
values
  (101, 3.00, 40, true, 1),
  (101, 5.00, 25, true, 2),
  (101, 10.00, 10, true, 3),
  (102, 3.00, 35, true, 1),
  (102, 5.00, 20, true, 2)
on conflict (product_id, weight_kg) do update
set
  stock_count = excluded.stock_count,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;

-- Admin insert/update examples
-- 1. Create product:
-- insert into products (name, slug, base_price_per_kg, description) values ('Banganapalli Mango', 'banganapalli-mango', 239, '...');
--
-- 2. Add variants:
-- insert into product_variants (product_id, weight_kg, stock_count) values (103, 3, 50), (103, 5, 30), (103, 10, 12);
--
-- 3. Update only the base price and all variant prices change automatically:
-- update products set base_price_per_kg = 259 where id = 103;
--
-- 4. Storefront/admin read query:
-- select * from product_variant_prices where product_is_active = true and variant_is_active = true and stock_count > 0 order by product_name, weight_kg;
