const fs = require('fs');
let content = fs.readFileSync('d:/Farmily Web/app.js', 'utf8');

// The exact string to find
const targetStr = `// 1. Create main order (order_number is generated by DB default)
          const { data: orderData, error: orderErr } = await supabaseClient
            .from('orders')
            .insert([{
              subtotal: tot - (tot > 1000 ? 0 : 49),
              delivery_charge: (tot > 1000 ? 0 : 49),
              total: tot,
              payment_status: 'paid',
              status: 'confirmed',
              customer_name: customerName,
              phone: phone,
              address: address
            }])
            .select()
            .single();`;

// The fixed version
const replacement = `// 0. Create guest address record for Admin compatibility
          let addressId = null;
          try {
            const { data: addrData } = await supabaseClient
              .from('addresses')
              .insert([{ 
                full_name: customerName, 
                phone: phone, 
                address_line: address, 
                city: 'Guest', 
                state: 'Order', 
                pincode: '000000' 
              }])
              .select().single();
            if (addrData) addressId = addrData.id;
          } catch (e) { console.error("Address sync failed:", e); }

          // 1. Create main order (order_number is generated by DB default)
          const { data: orderData, error: orderErr } = await supabaseClient
            .from('orders')
            .insert([{ 
              subtotal: tot - (tot > 1000 ? 0 : 49), 
              delivery_charge: (tot > 1000 ? 0 : 49), 
              total: tot, 
              payment_status: 'paid', 
              status: 'confirmed', 
              customer_name: customerName, 
              phone: phone, 
              address: address, 
              address_id: addressId 
            }])
            .select()
            .single();`;

if (content.indexOf('// 1. Create main order') >= 0) {
    // Normalize line endings for the match
    const normalizedContent = content.replace(/\r\n/g, '\n');
    const normalizedTarget = targetStr.replace(/\r\n/g, '\n');
    
    if (normalizedContent.includes(normalizedTarget)) {
        const finalContent = normalizedContent.replace(normalizedTarget, replacement.replace(/\r\n/g, '\n'));
        fs.writeFileSync('d:/Farmily Web/app.js', finalContent.replace(/\n/g, '\r\n'), 'utf8');
        console.log('SUCCESS: Injected address sync logic into app.js');
    } else {
        console.log('FAILED: Target block not found in content (Normalized test)');
        // Try a simpler match
        const simpleTarget = "customer_name: customerName,";
        if (content.includes(simpleTarget)) {
            console.log("Found 'customer_name: customerName,', performing partial swap...");
            const partialFixed = "customer_name: customerName,\n              phone: phone,\n              address: address,\n              address_id: addressId";
            const newContent = content.replace("customer_name: customerName,\n              phone: phone,\n              address: address", partialFixed);
            // This is risky, giving up on script and using a simpler approach
        }
    }
} else {
    console.log('FAILED: Start comment not found');
}
